# SPDX-FileCopyrightText: 2017-2022 EasyCoding Team
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
max_jobs: 1
image: Visual Studio 2019
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
install:
- cmd: >-
    set PATH=C:\Python310-x64;C:\Python310-x64\Scripts;%PATH%

    pip3 install -r requirements.txt

    pip3 install pyinstaller
build_script:
- cmd: >-
    set PATH=C:\Python310-x64;C:\Python310-x64\Scripts;%PATH%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    cd packaging\windows

    call build.cmd
test: off
artifacts:
- path: packaging\windows\results\snapshot_*.exe
  name: installer
deploy: off
