name: Question
description: Ask a question about the project
labels: [question]
body:
  - type: textarea
    attributes:
      label: Question
      placeholder: Ask a question about the project here.
    validations:
      required: true
